[package]
name = "csv-seal"
version = "0.1.0"
edition = "2024"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }

[addresses]
csv_seal = "0xeca5c0931e91d07d9ac47c7dfd767e43554150cff31de57d3da14f315de2ca55"
sui = "0x2"
