[package]
name = "csv-seal"
version = "0.2.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet" }

[addresses]
csv_seal = "_"
aptos_framework = "0x1"
CSV = "_"
