[package]
name = "csv-seal-v2"
version = "1.0.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet" }

[addresses]
csv_seal = "d9add20ef2b9a53affba7c2661ed61b2832b0ac8397c680b2ec0aa9919ef703e"
aptos_framework = "0x1"
CSV = "d9add20ef2b9a53affba7c2661ed61b2832b0ac8397c680b2ec0aa9919ef703e"
