[toolchain]
anchor_version = "1.0.2"

[features]
resolution = false
skip-lint = false

[programs.devnet]
csv_seal = "9ekKQYpaLkTrycYmRNRDHohYZwXycHAyfLNirUDRnRVh"

[programs.localnet]
csv_seal = "2nVbT9d33j1ySDdHHmNKUgthfV7RbyQDTqRua8192Tn6"

[programs.mainnet]
csv_seal = "HzZ12WPJjDvZ8nCA9yjXgKAoJ8XV1386976Jwrm63RcD"

[programs.testnet]
csv_seal = "HzZ12WPJjDvZ8nCA9yjXgKAoJ8XV1386976Jwrm63RcD"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
initialize = "bash ../scripts/initialize.sh"
lint = "cargo clippy"
test = "cargo test"

[hooks]
